
[package]
    archivePath = "https://d4i3qtqj3r0z5.cloudfront.net/omni.graph.tutorials-1.40.0%2B106.4.0.wx64.r.cp310.zip"

    [package.target]

        [package.target.config]
            0 = "release"

        [package.target.python]
            0 = "cp310"

        [package.target.platform]
            0 = "windows-x86_64"

        [package.target.kit]
            0 = "106.4.0"

    [package.publish]
        kitVersion = "106.4.0+master.147491.c3bdd56c.gl"
        date = 1729285557
        buildNumber = "23-06+master.6878.505b2301.gl"
        repoName = "kit-omnigraph"
        signed = 1
